# Node.js 이미지 사용
FROM node:14

# 작업 디렉토리 설정
WORKDIR /usr/src/app

# package.json 및 package-lock.json 복사
COPY package*.json ./

# 의존성 설치
RUN npm install

# 애플리케이션 소스 복사
COPY . .

# 애플리케이션 실행 포트
EXPOSE 3000

# 서버 실행 명령어
CMD ["node", "index.js"]
